// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/natsrpc/v1/envelope.proto

package natsrpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         uint32                 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	RpcId         uint32                 `protobuf:"varint,2,opt,name=rpc_id,json=rpcId,proto3" json:"rpc_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_natsrpc_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_natsrpc_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_natsrpc_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMsgId() uint32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Envelope) GetRpcId() uint32 {
	if x != nil {
		return x.RpcId
	}
	return 0
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Envelope) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_proto_natsrpc_v1_envelope_proto protoreflect.FileDescriptor

const file_proto_natsrpc_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/natsrpc/v1/envelope.proto\x12\n" +
	"natsrpc.v1\"\x8e\x02\n" +
	"\bEnvelope\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\rR\x05msgId\x12\x15\n" +
	"\x06rpc_id\x18\x02 \x01(\rR\x05rpcId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12;\n" +
	"\aheaders\x18\a \x03(\v2!.natsrpc.v1.Envelope.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B,Z*server/nats_rpc/proto/natsrpc/v1;natsrpcv1b\x06proto3"

var (
	file_proto_natsrpc_v1_envelope_proto_rawDescOnce sync.Once
	file_proto_natsrpc_v1_envelope_proto_rawDescData []byte
)

func file_proto_natsrpc_v1_envelope_proto_rawDescGZIP() []byte {
	file_proto_natsrpc_v1_envelope_proto_rawDescOnce.Do(func() {
		file_proto_natsrpc_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_natsrpc_v1_envelope_proto_rawDesc), len(file_proto_natsrpc_v1_envelope_proto_rawDesc)))
	})
	return file_proto_natsrpc_v1_envelope_proto_rawDescData
}

var file_proto_natsrpc_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_natsrpc_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil), // 0: natsrpc.v1.Envelope
	nil,              // 1: natsrpc.v1.Envelope.HeadersEntry
}
var file_proto_natsrpc_v1_envelope_proto_depIdxs = []int32{
	1, // 0: natsrpc.v1.Envelope.headers:type_name -> natsrpc.v1.Envelope.HeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_natsrpc_v1_envelope_proto_init() }
func file_proto_natsrpc_v1_envelope_proto_init() {
	if File_proto_natsrpc_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_natsrpc_v1_envelope_proto_rawDesc), len(file_proto_natsrpc_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_natsrpc_v1_envelope_proto_goTypes,
		DependencyIndexes: file_proto_natsrpc_v1_envelope_proto_depIdxs,
		MessageInfos:      file_proto_natsrpc_v1_envelope_proto_msgTypes,
	}.Build()
	File_proto_natsrpc_v1_envelope_proto = out.File
	file_proto_natsrpc_v1_envelope_proto_goTypes = nil
	file_proto_natsrpc_v1_envelope_proto_depIdxs = nil
}
